name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy Node.js app on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # Create/clean app directory
            rm -rf ~/nodejs-app
            mkdir -p ~/nodejs-app
            cd ~/nodejs-app

            # Clone your repo into this folder
            git clone https://github.com/NikitaSalunkhe11/deploy_nodeJS_app.git . || (git fetch origin && git reset --hard origin/main)

            # Create .env file from secrets if needed
            cat > .env << EOF
            PORT=80
            # add other ENV vars here
            EOF

            # Build Docker image
            sudo docker build -t nodejs-app:latest .

            # Stop & remove old container if it exists
            sudo docker stop nodejs-app || true
            sudo docker rm nodejs-app || true

            # Run the new container
            sudo docker run -d \
              --name nodejs-app \
              --env-file .env \
              -p 5000:5000 \
              nodejs-app:latest

            # Cleanup old images
            sudo docker image prune -f
