name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy Node.js app on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            rm -rf ~/nodejs-app
            mkdir -p ~/nodejs-app
            cd ~/nodejs-app
            git clone https://github.com/NikitaSalunkhe11/deploy_nodeJS_app.git . || (git fetch origin && git reset --hard origin/main)

            cat > .env << EOF
            PORT=${{ secrets.PORT }}
            EOF

            sudo docker build -t nodejs-app:latest .
            sudo docker stop nodejs-app || true
            sudo docker rm nodejs-app || true
            sudo docker run -d --name nodejs-app --env-file .env -p ${{ secrets.PORT }}:${{ secrets.PORT }} nodejs-app:latest
            sudo docker image prune -f
