name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy Node.js app on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # Prepare app directory
            rm -rf ~/nodejs-app
            mkdir -p ~/nodejs-app
            cd ~/nodejs-app

            # Clone your Node.js repo (or pull if repo already cloned)
            git clone https://github.com/NikitaSalunkhe11/deploy_nodeJS_app.git . || (git fetch origin && git reset --hard origin/main)

            # Create .env file from secrets
            cat > .env << EOF
            PORT=${{ secrets.PORT }}
            # Add other env vars here if needed
            EOF

            # Build Docker image
            sudo docker build -t nodejs-app:latest .

            # Stop & remove old container if exists
            sudo docker stop nodejs-app || true
            sudo docker rm nodejs-app || true

            # Run new container with env file and port mapping
            sudo docker run -d \
              --name nodejs-app \
              --env-file .env \
              -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              nodejs-app:latest

            # Clean dangling images
            sudo docker image prune -f
